services:

  db:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .mysql.env
    restart: unless-stopped

  django:
    container_name: django-EPG
    build:
      context: ./
      dockerfile: ./.docker/django/Dockerfile
    command: ash -c 'sleep 4 && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./:/opt
    restart: unless-stopped

  node:
    container_name: node-EPG
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    volumes: 
      - ./react:/opt/app/
    restart: unless-stopped

  nginx:
    container_name: nginx-EPG
    build:
      context: ./.docker/nginx
      args:
        ENABLED_MODULES: brotli headers-more modsecurity
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/templates:/etc/nginx/templates:ro
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    restart: unless-stopped

  